/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'admins': RouteRecordInfo<'admins', '/admins', Record<never, never>, Record<never, never>>,
    'admins-id-change-password': RouteRecordInfo<'admins-id-change-password', '/admins/:id/change-password', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admins-id-edit': RouteRecordInfo<'admins-id-edit', '/admins/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admins-create': RouteRecordInfo<'admins-create', '/admins/create', Record<never, never>, Record<never, never>>,
    'customers': RouteRecordInfo<'customers', '/customers', Record<never, never>, Record<never, never>>,
    'customers-id': RouteRecordInfo<'customers-id', '/customers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'forgot-passwordv2': RouteRecordInfo<'forgot-passwordv2', '/forgot-passwordv2', Record<never, never>, Record<never, never>>,
    'inquiries': RouteRecordInfo<'inquiries', '/inquiries', Record<never, never>, Record<never, never>>,
    'inquiries-id': RouteRecordInfo<'inquiries-id', '/inquiries/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'loginv2': RouteRecordInfo<'loginv2', '/loginv2', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-about-us': RouteRecordInfo<'pages-about-us', '/pages/about-us', Record<never, never>, Record<never, never>>,
    'pages-cookie': RouteRecordInfo<'pages-cookie', '/pages/cookie', Record<never, never>, Record<never, never>>,
    'pages-privacy': RouteRecordInfo<'pages-privacy', '/pages/privacy', Record<never, never>, Record<never, never>>,
    'pages-terms': RouteRecordInfo<'pages-terms', '/pages/terms', Record<never, never>, Record<never, never>>,
    'pages-user-profile-tab': RouteRecordInfo<'pages-user-profile-tab', '/pages/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'testimonials': RouteRecordInfo<'testimonials', '/testimonials', Record<never, never>, Record<never, never>>,
    'testimonials-id-edit': RouteRecordInfo<'testimonials-id-edit', '/testimonials/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'testimonials-create': RouteRecordInfo<'testimonials-create', '/testimonials/create', Record<never, never>, Record<never, never>>,
  }
}
