<?php

return [
    'ACTIVE_STATUSES' => [1 => 'Active', 0 => 'Inactive'],
    'REMEMBER_TOKEN_EXPIRED' => env('REMEMBER_TOKEN_EXPIRED', 525600),
    'pagination_per_page' => env('PAGINATION_PER_PAGE', 20),
    'enable_https' => env('ENABLE_HTTPS', false),
    'otp_expire_after' => env('OTP_EXPIRE_AFTER', '10'),
    'app_url' => env('APP_URL', 'sezl-admin.com'),
    'contact_email' => env('CONTACT_EMAIL', 'contact@sezl-admin.com'),
    'mail_from_email' => env('MAIL_FROM_ADDRESS', 'info@sezl-admin.com'),
    'settings' => [
        'site_name' => 'site_name',
        'site_title' => 'site_title',
        'site_email' => 'site_email',
        'site_contact_numbers' => 'site_contact_numbers',
        'site_address' => 'site_address',
        'site_facebook_url' => 'site_facebook_url',
        'site_instagram_url' => 'site_instagram_url',
        'site_x_url' => 'site_x_url',
        'site_youtube_url' => 'site_youtube_url',
        'site_linkedin_url' => 'site_linkedin_url',
        'site_tiktok_url' => 'site_tiktok_url',
        'site_whatsapp_number' => 'site_whatsapp_number',
        'site_footer_content' => 'site_footer_content',
    ],
    'testimonial_types' => [
        'client' => 'Client',
        'graduate' => 'Graduate',
    ],
    'card_types' => [
        'why_us_bd' => 'why_us_bd',
        'why_us_sezl' => 'why_us_sezl',
        'why_us_partner' => 'why_us_partner',
        'why_us_incentive' => 'why_us_incentive',
        'facilities_infrastructure' => 'facilities_infrastructure',
        'facilities_business' => 'facilities_business',
        'training' => 'training',
        'zone_highlights' => 'zone_highlights',
        'career' => 'career',
    ],
];
